### PR TITLE
[fix] cannot generate outfile whose name contains space

### PR DESCRIPTION
**Pull request by keineahnung2345**
If there is a space in file name, it can't be generated by the original pandoc command, error message:
```
Started GET "/projects/project1/repository/temp/preview/preview_files/xxx yyy.html@/index.html" for 192.168.1.1 at 2022-04-14 11:35:13 +0800
Processing by RepositoriesController#more_preview as HTML
  Parameters: {"id"=>"project1", "repository_id"=>"temp", "path"=>"preview_files/xxx yyy.html"}
  Current user: username (id=5)
Creating preview with Mark failed (pid 309718 exit 1):
Command: cd '/tmp/d20220414-308805-1q6tcw'; pandoc '/tmp/d20220414-308805-1jzw0ha/xxx yyy.html' -f html -t html -s -V header-includes='<base href='"'"'/projects/project1/repository/temp/raw/preview_files/xxx yyy.html'"'"'>' -o xxx yyy.html; mv 'xxx yyy.html' '/tmp/d20220414-308805-1q6tcw/index.html'
An error occured while generating preview for /tmp/d20220414-308805-1jzw0ha/xxx yyy.html
Exception was: RedmineMorePreviews::Exceptions::ConverterShellError
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:322:in `command'
/home/redmine/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:50:in `convert'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:188:in `block in transient_preview'
/usr/share/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:181:in `transient_preview'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:203:in `cached_preview'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:167:in `block in preview'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:132:in `synchronize'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:132:in `sync'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:167:in `preview'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:332:in `convert'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repository_patch.rb:44:in `block in more_preview'
/usr/share/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repository_patch.rb:41:in `more_preview'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repositories_controller_patch.rb:94:in `send_more_preview'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repositories_controller_patch.rb:61:in `block (2 levels) in more_preview'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
/home/redmine/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/repositories_controller_patch.rb:60:in `more_preview'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/base.rb:194:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/redmine/redmine/lib/redmine/sudo_mode.rb:65:in `sudo_mode'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications.rb:168:in `instrument'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/abstract_controller/base.rb:134:in `process'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionview-5.2.4.5/lib/action_view/rendering.rb:32:in `process'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal.rb:191:in `dispatch'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_controller/metal.rb:252:in `dispatch'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/rack/logger.rb:38:in `call_app'
/usr/share/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/rack/logger.rb:26:in `block in call'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/share/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/rack/logger.rb:26:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.5/lib/rails/engine.rb:524:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
/usr/share/rvm/gems/ruby-2.6.6/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
/usr/share/rvm/gems/ruby-2.6.6/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/share/rvm/gems/ruby-2.6.6/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/share/rvm/gems/ruby-2.6.6/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/share/rvm/gems/ruby-2.6.6/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/share/rvm/gems/ruby-2.6.6/gems/passenger-6.0.8/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
  Rendering text template
  Rendered text template (0.0ms)
Sent data index.html (0.7ms)
Completed 200 OK in 82ms (Views: 0.5ms | ActiveRecord: 22.4ms)
```

### CODE REVIEW

**Comment by HugoHasenbein** [comment]
i will look into this

**Comment by HugoHasenbein** [comment]
could not reproduce the error here, but added a prudent fix, so it should work now

**Comment by keineahnung2345** [comment]
It happens when previewing html file with space in its name.
By the way, you could actually merge this.

**Comment by ashrafalzyoud** [comment]
kkk

**Comment by HugoHasenbein** [comment]
this is not redmine_more_preview-code

**Comment by ashrafalzyoud** [comment]
this happend when activate the plugin
the msg in eindex of
wwwww

**Comment by ashrafalzyoud** [comment]
oooo


i think this version in jquery 3.6 not support E-INDEXOF

**Pull request closed without merging**
